# Generated by Django 4.0.2 on 2022-06-29 10:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('medicine', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buying',
            old_name='Buyer',
            new_name='buyer',
        ),
        migrations.RenameField(
            model_name='donating',
            old_name='Amount',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='prescription',
            old_name='Buyer',
            new_name='buyer',
        ),
        migrations.AlterField(
            model_name='donating',
            name='donor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
