# Generated by Django 4.0.2 on 2022-06-29 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0003_rename_buying_purchasing'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='units',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
