# Generated by Django 4.0.2 on 2022-07-10 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0004_rename_amount_donating_donation_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calculationunits',
            old_name='donations',
            new_name='donation_amount',
        ),
        migrations.RenameField(
            model_name='calculationunits',
            old_name='price',
            new_name='set_price',
        ),
        migrations.RenameField(
            model_name='calculationunits',
            old_name='sales',
            new_name='units_sold',
        ),
    ]
