# Generated by Django 4.0.2 on 2022-07-05 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0004_medicine_units'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donating',
            name='amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchasing',
            name='units',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
