# Generated by Django 4.0.2 on 2022-07-10 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0005_rename_donations_calculationunits_donation_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='set_price',
        ),
        migrations.AddField(
            model_name='mediunits',
            name='set_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
