# Generated by Django 4.0.2 on 2022-07-10 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0006_remove_medicine_set_price_mediunits_set_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculationunits',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
