# Generated by Django 4.0.2 on 2022-07-05 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0006_disease_alter_medicine_disease'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
