# Generated by Django 4.0.2 on 2022-07-10 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0007_calculationunits_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calculationunits',
            name='datetime',
        ),
    ]
