# Generated by Django 4.0.2 on 2022-07-05 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0008_alter_medicine_disease'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='disease',
            field=models.CharField(max_length=30),
        ),
    ]
