# Generated by Django 4.0.2 on 2022-07-10 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0008_remove_calculationunits_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculationunits',
            name='medicine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medicine.medicine'),
        ),
        migrations.AlterField(
            model_name='calculationunits',
            name='donation_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calculationunits',
            name='set_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calculationunits',
            name='units',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calculationunits',
            name='units_sold',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
