# Generated by Django 4.0.2 on 2022-07-10 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0009_calculationunits_medicine_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calculationunits',
            old_name='medicine',
            new_name='medicine_id',
        ),
    ]
