# Generated by Django 4.0.2 on 2022-07-05 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0009_alter_disease_name_alter_medicine_disease'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='disease',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medicine.disease'),
        ),
    ]
