# Generated by Django 4.0.2 on 2022-07-11 07:03

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0011_calculationunits_disease_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease',
            name='picture',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
