# Generated by Django 4.0.2 on 2022-07-05 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0011_alter_medicine_picture_alter_prescription_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
