# Generated by Django 4.0.2 on 2022-07-06 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0013_donating_email_donating_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donating',
            name='medicine',
        ),
        migrations.AddField(
            model_name='donating',
            name='disease',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medicine.disease'),
        ),
    ]
