# Generated by Django 4.0.2 on 2022-07-07 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0014_remove_donating_medicine_donating_disease'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='disease',
            options={'verbose_name_plural': 'Diseases'},
        ),
        migrations.AlterModelOptions(
            name='donating',
            options={'verbose_name_plural': 'Donations'},
        ),
        migrations.AlterModelOptions(
            name='medicine',
            options={'verbose_name_plural': 'Medicines'},
        ),
        migrations.AlterModelOptions(
            name='prescription',
            options={'verbose_name_plural': 'Prescriptions'},
        ),
        migrations.AlterModelOptions(
            name='purchasing',
            options={'verbose_name_plural': 'Purchases'},
        ),
    ]
