# Generated by Django 4.0.2 on 2022-07-07 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0015_alter_disease_options_alter_donating_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediUnits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('units', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Medicine Units',
            },
        ),
    ]
