# Generated by Django 4.0.2 on 2022-07-07 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0016_mediunits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='units',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medicine.mediunits'),
        ),
    ]
