# Generated by Django 4.0.2 on 2022-07-07 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0017_alter_medicine_units'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='units',
        ),
        migrations.AddField(
            model_name='mediunits',
            name='medicine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medicine.medicine'),
        ),
    ]
